site_name: Fintech Club Documentation
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/ROUNDED_ICON.png
  favicon: assets/ROUNDED_ICON.png
  font:
    text: Poppins
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    #- navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.path
    - navigation.footer

copyright: Copyright &copy; 2024 - 2025 UB Fintech Club Material

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/TEZqRNvfwn
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ub_fintech
    - icon: fontawesome/brands/slack
      link: https://buffalo.campuslabs.com/engage/organization/fintech
plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Code Docs:
    - Java: coding/javafile.md
  - About: 
    - Current Projects: about/projects.md
    - About Me: about/about.md
    - Childhood: about/childhood.md
  - Tags: tags.md
  - Blog: 
    - blog/index.md